platform :ios, '5.0'
pod 'Kiwi', '1.1.0'
pod 'GHUnitIOS'
pod 'OCMock'
pod 'NLTHTTPStubServer', '0.1.4'
pod 'AFNetworking'
pod 'AFOAuth2Client'
pod 'MagicalRecord'
pod 'TTTAttributedLabel'
pod 'JASidePanels'
pod 'KissXML'
pod 'EEHUDView'
pod 'UIGlossyButton'
