platform :ios, '5.0'
pod 'Kiwi', '1.1.0'
pod 'NLTHTTPStubServer', '0.1.3'
pod 'AFNetworking'
pod 'MagicalRecord'
pod 'TTTAttributedLabel'
pod 'JASidePanels'
pod 'EEHUDView'
pod 'UIGlossyButton'
pod 'SVPullToRefresh'
pod 'JMImageCache'
pod 'Overline'
